#!/usr/bin/env python

import argparse
import os
import sys
import time

if os.name == 'nt':
    sys.path.append(os.path.dirname(os.path.realpath(__file__)) + "/../src/")
from dragonfly_speech_recognition.dragonfly_client import DragonflyClient


parser = argparse.ArgumentParser()
parser.add_argument("--ip", default="localhost", type=str)
parser.add_argument("--port", default=3000, type=int)

args = parser.parse_args()

c = DragonflyClient(args.ip, args.port)
while True:
    print(c.recognize("T -> yes | no", "T"))
    time.sleep(1)
