#!/usr/bin/env python

import os
import sys
import time

if os.name == 'nt':
    sys.path.append(os.path.dirname(os.path.realpath(__file__)) + "/../src/")

from dragonfly_speech_recognition.recorder import Recorder

print("[TEST]: Constructing recorder")
rec = Recorder()

for i in range(2):
    print("[TEST]: Starting recorder {} at {}".format(i, time.strftime("%H:%M:%S")))
    rec.start()

    print("[TEST]: Start sleeping {} at {}".format(i, time.strftime("%H:%M:%S")))
    time.sleep(2.0)
    print("[TEST]: Done sleeping")

    print("[TEST]: Stopping recorder {} at {}".format(i, time.strftime("%H:%M:%S")))
    rec.stop()

    time.sleep(1.0)

    print("[TEST]: Done {} at {}".format(i, time.strftime("%H:%M:%S")))

print("[TEST] Done!")
