#!/usr/bin/env python
import os
import sys
import argparse

if os.name == 'nt':
    sys.path.append(os.path.dirname(os.path.realpath(__file__)) + "/../src/")
from dragonfly_speech_recognition.dragonfly_server import DragonflyServer


parser = argparse.ArgumentParser()
parser.add_argument("--ip", default="localhost", type=str)
parser.add_argument("--port", default=3000, type=int)

args = parser.parse_args()

print "Setting up DragonflyServer {}:{}".format(args.ip, args.port)
c = DragonflyServer(args.ip, args.port)

print "Spinning ..."
c.spin()
