#!/usr/bin/env python
import rospy
from dragonfly_speech_recognition.hmi_server_dragonfly_client import HMIServerDragonflyClient

if __name__ == "__main__":
    rospy.init_node('hmi_server_dragonfly_client')
    c = HMIServerDragonflyClient()
    rospy.spin()
