#!/usr/bin/env python

import rospy

from hmi_server.abstract_server import AbstractHMIServer
from hmi_msgs.msg import QueryAction, Choice
from compiler.ast import flatten
from multiprocessing.connection import Client
from array import array
from argparse import ArgumentParser
from xmlrpclib import ServerProxy
from time import sleep
from hmi_server.abstract_server import HMIResult

class RosServer(AbstractHMIServer):

    def __init__(self, ros_name, ip):
        self._ip = ip
        super(RosServer, self).__init__(ros_name)

    def _determine_answer(self, description, spec, choices, is_preempt_requested):

        address = (self._ip, 8000)
        rospy.loginfo('making a client')
        conn = Client(address)

        rospy.loginfo('sending...')
        conn.send(['set', description, spec, choices])

        rospy.loginfo('waiting for result')
        while not conn.poll(.1):
            # rospy.loginfo('polling...')
            if is_preempt_requested():
                rospy.loginfo('preempt requested')
                return None

        msg = conn.recv()

        rospy.loginfo('received result: %s', msg)
        conn.close()

        return HMIResult(raw_result=msg[0], results=msg[1])


if __name__ == '__main__':

    rospy.init_node('ros_speech_bridge')
    argv = rospy.myargv()

    parser = ArgumentParser()
    parser.add_argument('query', nargs="?", help='Test query')

    args = parser.parse_args(argv[1:])
    query = args.query

    if query:
        class TestServer(RosServer):
            def __init__(self):
                self._ip = 'localhost'
        server = TestServer()
        server._determine_answer('test', query, None)

    else:

        try:
            if rospy.has_param('~ip'):
                ip = rospy.get_param('~ip')
                server = RosServer(rospy.get_name(), ip)
                rospy.loginfo("GetSpeech client initialized [connecting to server on ip %s]", ip)
                rospy.spin()
            else:
                rospy.logerr("GetSpeech client: no server ip set; please specify the local 'ip' parameter")
        except rospy.ROSInterruptException:
            pass
